### ISSUE TITLE
For developers or for end users?

### ISSUE THREAD

**Issue by szepeviktor** [billerickson/BE-Starter#9]
If this repo is a starter then it should be a template
![image](https://github.com/billerickson/BE-Starter/assets/952007/0cb61c55-2568-4569-9350-4efb2adf987f)

If it is for end users then we need two branches
1. develop - for development
2. trunk or production - for WP.org releases

**Comment by szepeviktor** [comment]
Based on https://www.billerickson.net/hybrid-wordpress-theme-starter/ I think it is "for developers"

**Comment by billerickson** [comment]
Updated: https://a.cl.ly/Wnu6zpbe
